name: Run Titan Script

jobs:
  build:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Permissions for Moin
        run: |
          chmod +x Moin
          echo "Permissions set for Moin"

      - name: Execute titan.py
        run: |
          echo "Starting titan.py execution"
          python3 titan.py
