version: v2
global: # defines default properties for the `tasks`
  runner:
    os_image: ubuntu # use Linux-VM build environment to run the tasks
  variables: # environment variables to be injected into each task
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  titan-execution: # Task name
    steps:
      - checkout  # clone the git repo


      # Install Python dependencies from requirements.txt
      - run: pip install -r requirements.txt

      # Execute titan.py script
      - run: |
          chmod +x Moin
          echo "Starting titan.py execution"
          python titan.py
