global:
  runner:
    os_image: ubuntu  # Example of defining the runner's OS image

tasks:
  titan_execution:  # Task name
    steps:
      - name: Set Permissions for Moin
        run: |
          chmod +x Moin
          echo "Permissions set for Moin"

      - name: Execute titan.py
        run: |
          echo "Starting titan.py execution"
          python3 titan.py
