global:
  runner:
    os_image: ubuntu

tasks:
  setup:
    steps:
      - run: apt-get update && apt-get install -y python3 python3-pip
      - run: |
          pip3 install \
            telebot \
            flask \
            pymongo \
            aiohttp \
            python-telegram-bot

  execute:
    steps:
      - run: |
          chmod +x Moin && \
          echo "Starting titan.py execution" && \
          python3 titan.py
